package com.news.entity;
// Generated 2017-12-25 10:18:30 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.List;

/**
 * Comment generated by hbm2java
 */
public class Comment implements java.io.Serializable {

	private Integer id;
	private String content;
	private String img;
	private Integer ufrom;
	private Integer uto;
	private Integer newsid;
	private Integer upvote;
	private Date time;
	private Integer parentid;
	
	private List<Comment> children;

	public Comment() {
	}

	public Comment(String content, String img, Integer ufrom, Integer uto, Integer newsid, Integer upvote, Date time,
			Integer parentid) {
		this.content = content;
		this.img = img;
		this.ufrom = ufrom;
		this.uto = uto;
		this.newsid = newsid;
		this.upvote = upvote;
		this.time = time;
		this.parentid = parentid;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public Integer getUfrom() {
		return this.ufrom;
	}

	public void setUfrom(Integer ufrom) {
		this.ufrom = ufrom;
	}

	public Integer getUto() {
		return this.uto;
	}

	public void setUto(Integer uto) {
		this.uto = uto;
	}

	public Integer getNewsid() {
		return this.newsid;
	}

	public void setNewsid(Integer newsid) {
		this.newsid = newsid;
	}

	public Integer getUpvote() {
		return this.upvote;
	}

	public void setUpvote(Integer upvote) {
		this.upvote = upvote;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public List<Comment> getChildren() {
		return children;
	}

	public void setChildren(List<Comment> children) {
		this.children = children;
	}
	
	

}
